import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header/Header';
import HeroSlider from '../components/HeroSlider/HeroSlider';

export default function Home() {
  return (
    <div className='home'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main >
        <HeroSlider />
      </main>

      <footer>
      </footer>
    </div>
  )
}
